# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iq180.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0biq180.proto\x12\x0f\x63om.chula.iq180\"B\n\x13SubmitAnswerRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\x0c\"+\n\x14SubmitAnswerResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x03\"\x10\n\x0eGetTimeRequest\"\x1f\n\x0fGetTimeResponse\x12\x0c\n\x04time\x18\x01 \x01(\t\"\x12\n\x10HandCheckRequest\"#\n\x11HandCheckResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\" \n\x10\x45nterGameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"7\n\x11\x45nterGameResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x03\x12\r\n\x05token\x18\x02 \x01(\t2\xe2\x02\n\x05IQ180\x12T\n\tHandCheck\x12!.com.chula.iq180.HandCheckRequest\x1a\".com.chula.iq180.HandCheckResponse\"\x00\x12T\n\tEnterGame\x12!.com.chula.iq180.EnterGameRequest\x1a\".com.chula.iq180.EnterGameResponse\"\x00\x12N\n\x07GetTime\x12\x1f.com.chula.iq180.GetTimeRequest\x1a .com.chula.iq180.GetTimeResponse\"\x00\x12]\n\x0cSubmitAnswer\x12$.com.chula.iq180.SubmitAnswerRequest\x1a%.com.chula.iq180.SubmitAnswerResponse\"\x00\x42\x10\n\x0c\x63om.chula.iqP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iq180_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014com.chula.iqP\001'
  _globals['_SUBMITANSWERREQUEST']._serialized_start=32
  _globals['_SUBMITANSWERREQUEST']._serialized_end=98
  _globals['_SUBMITANSWERRESPONSE']._serialized_start=100
  _globals['_SUBMITANSWERRESPONSE']._serialized_end=143
  _globals['_GETTIMEREQUEST']._serialized_start=145
  _globals['_GETTIMEREQUEST']._serialized_end=161
  _globals['_GETTIMERESPONSE']._serialized_start=163
  _globals['_GETTIMERESPONSE']._serialized_end=194
  _globals['_HANDCHECKREQUEST']._serialized_start=196
  _globals['_HANDCHECKREQUEST']._serialized_end=214
  _globals['_HANDCHECKRESPONSE']._serialized_start=216
  _globals['_HANDCHECKRESPONSE']._serialized_end=251
  _globals['_ENTERGAMEREQUEST']._serialized_start=253
  _globals['_ENTERGAMEREQUEST']._serialized_end=285
  _globals['_ENTERGAMERESPONSE']._serialized_start=287
  _globals['_ENTERGAMERESPONSE']._serialized_end=342
  _globals['_IQ180']._serialized_start=345
  _globals['_IQ180']._serialized_end=699
# @@protoc_insertion_point(module_scope)
