# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import iq180_pb2 as iq180__pb2


class IQ180Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandCheck = channel.unary_unary(
                '/com.chula.iq180.IQ180/HandCheck',
                request_serializer=iq180__pb2.HandCheckRequest.SerializeToString,
                response_deserializer=iq180__pb2.HandCheckResponse.FromString,
                )
        self.EnterGame = channel.unary_unary(
                '/com.chula.iq180.IQ180/EnterGame',
                request_serializer=iq180__pb2.EnterGameRequest.SerializeToString,
                response_deserializer=iq180__pb2.EnterGameResponse.FromString,
                )
        self.GetTime = channel.unary_unary(
                '/com.chula.iq180.IQ180/GetTime',
                request_serializer=iq180__pb2.GetTimeRequest.SerializeToString,
                response_deserializer=iq180__pb2.GetTimeResponse.FromString,
                )
        self.SubmitAnswer = channel.unary_unary(
                '/com.chula.iq180.IQ180/SubmitAnswer',
                request_serializer=iq180__pb2.SubmitAnswerRequest.SerializeToString,
                response_deserializer=iq180__pb2.SubmitAnswerResponse.FromString,
                )


class IQ180Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnterGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IQ180Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HandCheck,
                    request_deserializer=iq180__pb2.HandCheckRequest.FromString,
                    response_serializer=iq180__pb2.HandCheckResponse.SerializeToString,
            ),
            'EnterGame': grpc.unary_unary_rpc_method_handler(
                    servicer.EnterGame,
                    request_deserializer=iq180__pb2.EnterGameRequest.FromString,
                    response_serializer=iq180__pb2.EnterGameResponse.SerializeToString,
            ),
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=iq180__pb2.GetTimeRequest.FromString,
                    response_serializer=iq180__pb2.GetTimeResponse.SerializeToString,
            ),
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=iq180__pb2.SubmitAnswerRequest.FromString,
                    response_serializer=iq180__pb2.SubmitAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.chula.iq180.IQ180', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IQ180(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.chula.iq180.IQ180/HandCheck',
            iq180__pb2.HandCheckRequest.SerializeToString,
            iq180__pb2.HandCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnterGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.chula.iq180.IQ180/EnterGame',
            iq180__pb2.EnterGameRequest.SerializeToString,
            iq180__pb2.EnterGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.chula.iq180.IQ180/GetTime',
            iq180__pb2.GetTimeRequest.SerializeToString,
            iq180__pb2.GetTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.chula.iq180.IQ180/SubmitAnswer',
            iq180__pb2.SubmitAnswerRequest.SerializeToString,
            iq180__pb2.SubmitAnswerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
